name: wt_firepod_chat
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/tmcmaster/wt_firepod_chat
publish_to: 'none'

flutter:

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: flutter analyze
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
    fix: dart pub add build_runner --dev
    rebuild: rps freezed fix; rps freezed build

dependencies:
  cloud_firestore: ^4.13.3
  faker: ^2.1.0
  file_picker: ^6.0.0
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_firebase_chat_core: ^1.6.7
  flutter_riverpod: ^2.4.3
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  http: ^1.1.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.1.1
  wt_app_scaffold:
    git:
      url: https://github.com/tmcmaster/wt_app_scaffold.git
  wt_firepod:
    git:
      url: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git:
      url: https://github.com/tmcmaster/wt_models.git

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:

dependency_overrides:
  wt_app_scaffold:
    path: ../wt_app_scaffold
  wt_firepod:
    path: ../wt_firepod
  wt_logging:
    path: ../wt_logging


